### ISSUE TITLE
Question about error handling

### ISSUE THREAD

**Issue by charles-lunarg** [YvesBoyadjian/vk-bootstrap4j#1]
First, pretty cool to see vk-bootstrap used outside of C++ :)

Looking at the error handling, I noticed its a rather straight copy of the vk-bootstrap code. The gist of why vk-bootstrap's C++ error handling is that way is because VkResult and regular error codes in general in C++ are not good. But exceptions aren't desireable either. `Result<T>` style "Either get an object or an error" is my preferred choice but to keep external dependencies down, I chose to make a ad-hoc Result<T> type. While I'm not java expert, I did some amount of it in university, and from that I would of assumed that exceptions are more idiomatic. Though, I've heard that java has gotten more 'functional programming' type features as of late, and maybe they have a standard library Result<T> type that could be used instead.

Regardless, this is less of an issue and more just an observation.

**Comment by YvesBoyadjian** [comment]
Thanks for your feedback, I made this java port also because I think vk-bootstrap is very good to learn Vulkan. I made a quick search, and I found that :
[https://medium.com/@afcastano/monads-for-java-developers-part-2-the-result-and-log-monads-a9ecc0f231bb](url)
Instead of Result class, I could have used an unchecked exception, but I like to be informed when a computation can fail, so I think I will keep the code as it is.

**Comment by charles-lunarg** [comment]
Sounds good, I really was just curious.
